### PR TITLE
Change in precision settings to have more accurate output

### PR DESCRIPTION
**Pull request by kiwifb**
Changing the ratio between the number of bits of precision and the number of decimals printed. This is to try to make sure only accurately computed decimals are printed out in most case.
There are still corner cases where decimal printed are not accurate, most notably when the accurate result should be `0`.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Thanks for your work on this.  I'll be able to look at your changes (which I'm sure are a great improvement) after my term ends, i.e. from Dec 11.

**Comment by JohnCremona** [comment]
Quick comment: the mysterious factor of 3.33 which you have changed to 3.66 is an approximation to log(10)/log(2) = 3.321928 to is the number of bits per digit.  I rounded up.  Is there a justification for 3.66?

**Comment by kiwifb** [comment]
So that's what that factor is. I guess the fact it looked like an approximation of 10/3 through me off. But it makes sense.
My own factor of 3.66 is empirically determined and has a lot against it. But lets go to the beginning now that I have an idea where 3.33 comes from.

You have a relation between the number of bits of storage and the number of decimals they can represent. What you don't have from that relation is the number of decimal that stay accurate across computations. Just because you can represent `n` decimals doesn't mean they are accurate.
And that's mostly what's revealed by the difference in results between compilers.

I started with the idea that when you represented `n` digits, `n-b` are actually accurate. And my first experiment relied on the idea that `b` was a constant and I tried `b=2`. Unfortunately as seen by the failures once you examine them properly `b` increases with `n`. It appears to be `2` when `n=20` (comptest) but at `n=50` (telog) it may be up `5`.

So I tried to inverse the problem. Instead of `n` being the number of digits you can represent, let `n` be the number of accurate digits. It means you need more bits because you will throw noisy digits away. I had done some experiments with comptest to see how the last bits varied when I increased the number of bits. I replaced `n*3.33` by `(n+1)*3.33` and then `(n+2)*3.33` and a couple more after that. `n+2` was when things got stable for comptest. Increasing the number didn't have an impact on the `n` digits displayed of the result.

That's where `3.66` comes from. Assuming that the needed ratio is linear, I worked the factor at `n=20` from my previous experiment. So `3.66` is approximately `(20+2)*3.33/20`. As it happened it gives good results in the range of `n` tested by eclib testsuite. I am assuming the maximum `n` tested is `50` from telog.

So what's wrong with my factor `3.66`? 

- It comes from an assumption that the relation I seek is linear. There is no proof of that. Just because it works in the tested range is no proof.
- The estimate at `n=20` is probably an overestimate. I tested in increments of 3.33 instead of 1. If the rate of growth needed is only slightly higher than linear, it explains why it works up to the `n=50` range.
- Even if the relation is linear, because of the way I got to it, the factor may be bigger than it needs.
It could also be that adding a constant rather than changing the factor could be sufficient in that case.
- The only sure thing is that the needed factor is bigger than `3.33`.

There are a few hints that suggests that 3.66 (as approximately `3.33*1.1`) may be a good value but it would have to be tested on a bigger range of `n` to see if it holds at least empirically. Formal proof would be difficult to achieve.

**Comment by kiwifb** [comment]
Oh, well so I tried a few more things. At `n=20` a factor of 3.53 is enough. I tried to see what happened if I rounded it to 3.6 and look at what happened. That when I noticed that `n=100` in theight, tsat2 and tsat3, and that it is equal to `200` in tsat. To achieve numerical stability of all the digits in the tests for theight I had to crank up the factor to 3.8. 
The tests in tsat don't really help us work out what the factor would need to be at that level.
It looks like 3.66 just happens to be a value where tests match between gcc and clang.

**Comment by kiwifb** [comment]
Just something I think is worth noting because it is strange. Fudging the factor changed one ot the results of `tperiods` dramatically. On line 10 at the end.

**Comment by JohnCremona** [comment]
The thing about periods is that there are two complex numbers w1 and w2 which generate a lattice Z*w1+Z*w2 and lattices have many Z-bases.  There are normalizations in place which in principle make w1, w2 unique but there are corner cases with more than one normalized pair, where there is a tie-break condition.  It is such cases where a small perturbation can result in a different pair being regarded as normalized.

I still think we should get away from any of this decimal-to-binary precision conversion and move to using only bit precision.  I would like to try that, using a few more bits for the internal precision than the output precision.  But not until my term ends.

**Comment by kiwifb** [comment]
OK lets revisit that then. I may do some more experiments on my side to try to pin something for the accuracy.

**Comment by kiwifb** [comment]
All right. Back to this. So I looked at the documentation from `ntl` and I would have gone with a different formula. The current `p=ln(10)/ln(2)` is based on the idea that `2^-p ~ 10^-n` which means that you say the error is in the order of the nth digit. To secure the last digit better it would be better to take `10^-(n+1)` in that case the relative error is still potentially about `+/- 10^-n` if you want to secure the nth digit totally you have to go to `n+2`.
Next item for some operations the error is not `2^-p` but `2^-(p-1)` eclib uses these operations (exp amongst other). So I would have gone with
`2^-(p-1) ~ 10^-(n+2)` which leads to `p ~ 1+(n+2)ln(10)/ln(2)`.
Even this revised formula doesn't lead to numerical stability at `n=50` the error is about a 1000 more than expected. Which leads me to believe that there is a lot of cumulative errors going on. Are there a lot of potentially big loops in the computations?

**Comment by JohnCremona** [comment]
I'm now working on a different branch which gets rid of the use of decimal precision in the user interface, so the internal bit precision is set according to the user input (or is fixed depending on the program).  It still does a conversion (factor 0.3) in setting the decimal output precision since that is what NTL uses.

When I'm done I'll make a separate pull request for my branch and will invite testing on other platforms.

**Comment by JohnCremona** [comment]
I now have code (and slightly revised test input and output) using bit precision, which compilies and runs and passes all tests for me using either gcc or clang and either --disable-mpfp or not.  I just need to update the version number etc and then I'll upload it (as a separate branch called prec) which will trigger travis.

**Comment by dimpase** [comment]
It would be great to have it done, so that the Sage clang ticket can progress...

**Comment by JohnCremona** [comment]
Closing since PR#35 fixes this and more.

**Pull request closed without merging**
