### PR TITLE
update macros. if ntl is not found try enabling c++11, then try findi…

### PR DESCRIPTION
**Pull request by kiwifb**
…ng ntl again before giving up.

Also got rid of superfluous `ntl_found` variable - it wasn't used that much and could easily be rid of.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Thanks -- I'll test on the old NTL and then the new.

**Comment by kiwifb** [comment]
I don't remember if threads are on by default in newer `ntl`, you may have to set `NTL_THREAD_BOOST=on`. If it is off you won't be using `c++11` and be back to the behavior of the old version.

**Comment by kiwifb** [comment]
Any news on this? Once we get `givaro`/`fflas-ffpack`/`linbox` upgrade a big chunk of stuff will be ready for c++11 and I can hack `singular` and `flint` to work with a newer `ntl` and threads.

**Comment by JohnCremona** [comment]
Sorry I did not reply earlier, the comment came in the day before I started
4 weeks of being very busy and then I forgot.
I will merge in your patch as soon as I can.

**Comment by JohnCremona** [comment]
I have tested this as follows.  On one machine which still has NTL version 6.2.0 (and library libntl.so.4 ) it works fine.  On another machine I installed NTL version 9.7.1 (installed library is called /usr/local/lib/libntl.so.23) and rebuilt eclib and again it works fine.
These NTL Version numbers look odd to me but otherwise all is good for me.  
1. Should I also test with C++11 somehow enabled, whatever that means?  How should I do that?
2. I suppose I ought to increment the LT_REVISION and the distribution date before releasing this version?

**Comment by kiwifb** [comment]
C++11 is used when threads are enabled. You have to configure `ntl` like so:
```
./configure NTL_THREAD_BOOST=on ${whatever_other_options_you use)
```
This will test your compiler for C++11 support and then use C++11 threads in `ntl`. You may want to observe what happen without this PR or an appropriate CXXFLAGS.

**Comment by JohnCremona** [comment]
I should have said: on the machine on which I had installed the new NTL it all worked fine without your PR (with and without configuring with NTL_THREAD_BOOST=on).  I will test again with your patch.

**Comment by JohnCremona** [comment]
I just did that and it still works fine: your branch, both with and without NTL_THREAD_BOOST=on, new NTL.  So I will merge your branch (and retest, since there are several commits on the master which you do not have).

**Pull request merged**
