### PR TITLE
Install missing header

### PR DESCRIPTION
**Pull request by antonio-rojas**

### CODE REVIEW

**Comment by JohnCremona** [comment]
Thanks.

**Comment by JohnCremona** [comment]
I'm still getting errors with "make distcheck" relating to the target list_cubics ( a recently added program in proogs/) and will fix that too and make a new release (with no actual code changes).

**Comment by saraedum** [comment]
@JohnCremona I just had a look but `make distcheck` works fine for me actually.

**Comment by isuruf** [comment]
You probably need `-lpthread` at the end in the following
`g++ -std=gnu++11 -g -O2 -o .libs/solve_conic solve_conic.o  -lpthread ../libsrc/.libs/libec.so -lpari -lntl -Wl,-rpath -Wl,/home/jec/eclib/eclib-20180727/_inst/lib`

**Pull request merged**
